# Site settings
title: SANSUI | WENKE
description: 三歲的文學星空
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
user:
    fullname: 
        ja: 三歲 | 文學
        ja_hira: はしもと りょう
        ja_kata: SANSUI  WENKE
    en: SANSUI ZHAO
    occupation: 三歲文學
    email: sansui_z@126.com
    tel: 
    twitter_username: XIANG_BLQ
    facebook_username: ryoh.hashimoto
    instagram_username: hashimotoryoh
    github_username: hashimotoryoh
    qiita_username: hashimotoryoh
    note_username: hashimotoryoh

# Google-analytics
google-analytics:
    id: ""

exclude: ['package.json', 'src' , 'node_modules']
